<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('personalized_lessons', function (Blueprint $table) {
            if (!Schema::hasColumn('personalized_lessons', 'practical_examples')) {
                // JSON column to store examples generated by AI
                $table->json('practical_examples')->nullable()->after('personalized_content');
            }
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('personalized_lessons', function (Blueprint $table) {
            if (Schema::hasColumn('personalized_lessons', 'practical_examples')) {
                $table->dropColumn('practical_examples');
            }
        });
    }
};


