name: CI
on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, curl, dom, fileinfo, json, pdo_sqlite

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('server/composer.lock') }}

      - name: Install deps
        working-directory: server
        run: composer install --no-interaction --prefer-dist

      - name: App key
        working-directory: server
        run: php artisan key:generate --force

      - name: Run Laravel tests
        working-directory: server
        env:
          APP_ENV: testing
        run: php artisan test

      - name: Composer audit (optional)
        working-directory: server
        run: composer audit || true

  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build

      - name: Test (if present)
        working-directory: client
        run: npm run test --if-present -- --run

      - name: npm audit (optional)
        working-directory: client
        run: npm audit --audit-level moderate || true

  fastapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        working-directory: server-FastApi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        working-directory: server-FastApi
        run: ruff check . || true

      - name: Tests
        working-directory: server-FastApi
        run: pytest -q

      - name: pip check (optional)
        working-directory: server-FastApi
        run: pip check || true
